#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""<+Module Description.+>"""

import argparse


def main():
    """Run main."""
    parser = argparse.ArgumentParser()
    parser.add_argument("-b", "--boolflag", action="store_true",
                        help="Input file")
    args = parser.parse_args()
    print(args)
    return 0

if __name__ == '__main__':
    main()
