#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""<+Module Description.+>"""

from __future__ import division, print_function

import sys
import os
import itertools as it

<++>


def main():
    """Run main."""

    return 0

if __name__ == '__main__':
    main()
